# Site settings
title: YX's Profile
email: yuxi4ng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/patchwork-gh-pages-24"
url: "http://arvilyn.github.io"
twitter_username: NIL
github_username:  arvilyn
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
